apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
  annotations:
    configmanagement.gke.io/managed: disabled
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
